

Vagrant.configure("2") do |config|

    config.vm.define "node1" do |node1|
      node1.vm.box = "centos/7"
      #node1.vm.network "public_network"
    end

    config.vm.define "master" do |master|
      master.vm.box = "centos/7"
     # master.vm.network "public_network"
    end


    config.vm.provider "virtualbox" do |vb|
       vb.memory = "2048"
    end

    config.vm.network "private_network", type: "dhcp"
end
